fire-station-training-and-vehicle/fire-station-training-and-vehicle/Models/Metadata/Station.cs
using fire_station_training_and_vehicle.CustomValidation;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace fire_station_training_and_vehicle.Models
{
    [ModelMetadataType(typeof(StationMetadata))]
    public partial class Station
    {
    }
    public class StationMetadata
    {
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Address { get; set; }
        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"\(?\d{3}\)?-? *\d{3}-? *-?\d{4}", ErrorMessage = "Not a valid phone number")]
        public string? PhoneNumber { get; set; }
        public bool? IsDeleted { get; set; }
    }
}

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Models/Station.cs
using System;
using System.Collections.Generic;

namespace fire_station_training_and_vehicle.Models
{
    public partial class Station
    {
        public Station()
        {
            AspNetUsers = new HashSet<AspNetUser>();
            Vehicles = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Address { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fire_station_training_and_vehicle.Models;
using Microsoft.AspNetCore.Authorization;
using fire_station_training_and_vehicle.Services;

namespace fire_station_training_and_vehicle.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StationController : Controller
    {
        private readonly FireFighterContext _context;

        public StationController(FireFighterContext context)
        {
            _context = context;
        }

        // GET: Station
        public async Task<IActionResult> Index(int pg = 1)
        {
            int pageSize = 9;
            if (pg < 1)
            {
                pg = 1;
            }
            int rescCount = _context.Stations.Where(x => x.IsDeleted == false).Count();
            var pager = new Pagination(rescCount, pg, pageSize);
            int rescSkip = (pg - 1) * pageSize;
            this.ViewBag.Pager = pager;
            var station=await _context.Stations.Where(x=>x.IsDeleted==false).Skip(rescSkip).Take(pager.PageSize).ToListAsync();
            return View(station);
        }

        // GET: Station/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stations == null)
            {
                return NotFound();
            }

            var station = await _context.Stations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (station == null)
            {
                return NotFound();
            }

            return View(station);
        }

        // GET: Station/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Station/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Email,PhoneNumber")] Station station)
        {
            if (ModelState.IsValid)
            {
                station.IsDeleted = false;
                _context.Add(station);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Station created successfully!!";
                return RedirectToAction(nameof(Index));
            }
            return View(station);
        }

        // GET: Station/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Stations == null)
            {
                return NotFound();
            }

            var station = await _context.Stations.FindAsync(id);
            if (station == null)
            {
                return NotFound();
            }
            return View(station);
        }

        // POST: Station/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Email,IsDeleted,PhoneNumber")] Station station)
        {
            if (id != station.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(station);

                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Station edited successfully!!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StationExists(station.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(station);
        }

       
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Stations == null)
            {
                return Problem("Entity set 'FireFighterContext.Stations'  is null.");
            }
            var station = await _context.Stations.FindAsync(id);
            if (station != null)
            {
                station.IsDeleted=true;
                _context.Update(station);
                TempData["Success"] = "Station deleted successfully!!";

            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StationExists(int id)
        {
          return _context.Stations.Any(e => e.Id == id);
        }
    }
}

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Views/Station/Create.cshtml
@model fire_station_training_and_vehicle.Models.Station

@{
    ViewData["Title"] = "Add  Station";
}
<style>
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    .row {
        background: white;
        border-radius: 30px;
    }

    h1 {
        margin-left: 20px;
    }

</style>
<h1>Add Station</h1>


<div class="row mx-4 my-4 no-gutters">
    <div class="col-md-4">
        <form class="row g-3" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-6">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
       
            <div class="col-md-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div  class="col-12">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
              <div class="col-12">
                <div class="autocomplete-container" id="autocomplete-container">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" class="autocomplete-container" id="autocomplete-containerd" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <input type="submit" value="Add Station" class="btn btn2" />
            </div>
        </form>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Views/Station/Delete.cshtml
@model fire_station_training_and_vehicle.Models.Station

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Station</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Views/Station/Details.cshtml
@model fire_station_training_and_vehicle.Models.Station

@{
    ViewData["Title"] = "Station Details";
}

<h1>Details for @Html.DisplayFor(model => model.Name)</h1>

<div class="row ms-5 g-0"> 
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Views/Station/Edit.cshtml
@model fire_station_training_and_vehicle.Models.Station

@{
    ViewData["Title"] = "Edit Station";
}

<h1>Edit Station @Model.Name</h1>

<div class="row ms-5 g-0">
    <div class="col-md-4">
        <form class="row g-3" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="col-md-6">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="IsDeleted" class="form-label"></label>
                <input asp-for="IsDeleted" class="form-control" />
                <span asp-validation-for="IsDeleted" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-12">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="col-12">
                <div class="autocomplete-container" id="autocomplete-container">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" class="autocomplete-container" id="autocomplete-containerd" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <input type="submit" value="Save" class="btn btn2" />
            </div>
        </form>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

fire-station-training-and-vehicle/fire-station-training-and-vehicle/Views/Station/Index.cshtml
@model IEnumerable<fire_station_training_and_vehicle.Models.Station>
@using fire_station_training_and_vehicle.Services
@{
    Pagination pager = new Pagination();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

@{
    ViewData["Title"] = "Stations";
}

<h1>Stations</h1>

<div class="row ms-5 g-0">

    <div class="col-lg-10">
        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>

                        <td>
                            <a class="link-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a class="link-info" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a class="link-danger"  asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="container">
        @if (pager.TotalPages > 0)
        {
            <ul class="pagination">
                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Station" asp-action="Index" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Station" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                    </li>
                }
                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge==pager.CurrentPage?"active":"")">
                        <a class="page-link" asp-controller="Station" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>
                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Station" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Station" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
    
</div>